// typescript-pt/13_integracao_typescript_react/src/componentes/Contador.tsx
import React, {Component} from 'react'
import ContadorValor from './ContadorValor'
import './Contador.css'
import logRender from '../decorators/logRender'

interface IContadorProps {
  valorInicial?: number
}

interface IContadorState {
  valor: number
}

@logRender
export default class Contador
  extends Component<IContadorProps, IContadorState> {

  public state: IContadorState = {valor: this.props.valorInicial || 0}

  private setValor = (delta: number) => {
    this.setState({
      valor: this.state.valor + delta,
    })
  }

  render() {
    return (
      <div>
        <ContadorValor contador={this.state.valor || 1000}/>
        <button onClick={() => this.setValor(10)}>+</button>
        <button onClick={() => this.setValor(-10)}>-</button>
      </div>
    )
  }
}

// typescript-pt/14_integracao_typescript_vue_js/src/components/Contador.vue
<template>
  <div>
    <h1>Contador</h1>
    <h2>{{ valor }}</h2>
    <button @click="setValor(1)">+</button>
    <button @click="setValor(-1)">-</button>
  </div>
</template>
<script lang="ts">
import Vue from 'vue'

export default Vue.extend({
  props: {
    valorInicial: {
      type: Number,
      default: 0,
    },
  },
  data() {
    return {
      valor: this.valorInicial,
    }
  },
  methods: {
    setValor(delta: number) {
      this.valor += delta
    },
  },
})
</script>
<style>

</style>
